---
title: "Final Report"
subtitle: "due November 16, 2021 by 11:59 PM "
author: "Your names and team name here"
date: ""
output: pdf_document
---

# Load Packages

```{r load-packages, message = FALSE, warning = FALSE}
library(tidyverse) 
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(rgeos)
library(scales)
``` 

# Load Data
```{r load-data, message = FALSE, warning = FALSE}
library(readr)
h_spend <- read_csv("../data/Health-Spending.CSV")
wb_tot_lifeexp <- read_csv("../data/World Bank Life Exp.csv")
wb_f_lifeexp <- read_csv("../data/World Bank Female Life Exp.csv")
wb_m_lifeexp <- read_csv("../data/World Bank Male Life Exp.csv")
econ <- read_csv("../data/EconMetrics.csv")
econ <- select(econ, -4)
```

#Combine Datasets
```{r combine-lifeexp-data}
wb_tot_lifeexp_long <- pivot_longer(wb_tot_lifeexp, cols = "1990":"2020", names_to = "Year", values_to = "Total Life Expectancy")

wb_f_lifeexp_long <- wb_f_lifeexp %>%
  select(c(1:2,34:64)) %>%
  pivot_longer(cols = "1990":"2020", names_to = "Year", values_to = "Female Life Expectancy")

wb_m_lifeexp_long <- wb_m_lifeexp %>%
  select(c(1:2,34:64)) %>%
  pivot_longer(cols = "1990":"2020", names_to = "Year", values_to = "Male Life Expectancy")

lifeexp <- left_join(wb_tot_lifeexp_long, wb_f_lifeexp_long, by = c("Country Name", "Country Code", "Year"))

lifeexp <- left_join(lifeexp, wb_m_lifeexp_long, by = c("Country Name", "Country Code", "Year"))
```

```{r edit_econ_data}
yrs <- c(2011:2020)

colnames(econ) <- c("Country Name", "Country Code", "Series Name", yrs)
econ_temp <- econ %>%
  pivot_longer(cols = 4:13, names_to = "Year", values_to = "Value")
econ_temp2 <- econ_temp %>%
  group_by("Country Name") %>%
  pivot_wider(names_from = "Series Name", values_from = "Value") %>%
  ungroup()
econ_temp3 <- select(econ_temp2, -4)
econ2 <- filter(econ_temp3, !is.na(econ_temp3$'Country Code'))
j <- c(4:58)
econ2[j] <- lapply(econ2[j], unlist)
econ2[j] <- lapply(econ2[j], as.numeric)
```

```{r edit_h_spend}
h_spend2 <- select(h_spend, -1, -4)
colnames(h_spend2)[1:3] <- c("Country Name", "Country Code", "Year")
```

```{r combine_data}
full_data <- full_join(lifeexp, econ2, by = c("Country Name", "Country Code", "Year"))
full_data$Year = as.double(full_data$Year)
full_data <- full_join(full_data, h_spend2, by = c("Country Name", "Country Code", "Year"))
```

```{r desc_stats_health_spending}
#Below is the distribution of log of Mean total health spending per person (in PPP dollars)
full_data %>%
  filter(Year == 2018) %>%
  filter(is.na(the_per_cap_ppp_mean) == FALSE) %>%
ggplot(aes(x = log(the_per_cap_ppp_mean))) + 
  geom_histogram(fill = "blue") + 
  labs(
    x = "Log of Mean total health spending per person (in PPP dollars)",
    y = "Frequency",
    title = "Distribution of Health Care Spending"
  ) 

#NOTE: TO THE PLOT ABOVE, ADD NORMAL CURVE TO THE ABOVE DISTRIBUTION

#Below are a few quick summary stats for health spending per person
full_data %>%
  select(the_per_cap_ppp_mean) %>%
   filter(is.na(the_per_cap_ppp_mean) == FALSE) %>%
summary(the_per_cap_ppp_mean)

full_data %>%
 filter(Year == 2018) %>%
  filter(is.na(the_per_cap_ppp_mean) == FALSE) %>%
    filter(is.na(`GDP (current US$)`) == FALSE) %>%
ggplot(aes(x = `GDP (current US$)`, y = log(the_per_cap_ppp_mean))) + 
geom_point(fill = "blue") + 
 labs(
   x = "GDP (current US$)",
    y = "Log of Mean total health spending per person (in PPP dollars)",
    title = "GDP vs Health Care Spending"
  ) 

#Below, we're plotting a map of health spending around the world
# the classic dark-on-light theme for ggplot2 is nice for maps
theme_set(theme_bw())
# world contains the country information for plotting in addition to a lot of other information about the countries
world <- ne_countries(scale = "medium", returnclass = "sf")

healthspending.world <- merge(world, full_data, by.x="admin", by.y="Country Name")

ggplot(data = healthspending.world) +
    geom_sf(aes(fill = log(the_per_cap_ppp_mean))) +
    scale_fill_viridis_c(option = "plasma") +
    labs(x = "Longitude",
       y = "Latitude",
       title = "Health Spending Around the World",
       fill = "Log of Mean total health spending per person (in PPP dollars)")


#Now we're going to choose 5 countries and plot line graphs for trends in health spending over time
full_data %>%
  filter(`Country Name` == "Australia" | `Country Name` == "United States of America" |  `Country Name` == "Canada" |  `Country Name` == "China") %>%
ggplot(aes(x=Year, y=log(the_per_cap_ppp_mean), group = `Country Name`)) +
  geom_line(aes(linetype= `Country Name`))+
  geom_point(aes(shape=`Country Name`))

```

```{r desc_stats_health_outcomes}
#Converting total life expectancy from character to numeric
full_data$`Total Life Expectancy` = as.numeric(full_data$`Total Life Expectancy`)

#Plotting distribution of total life expectancy
full_data %>%
  filter(Year == 2018) %>%
  filter(is.na(`Total Life Expectancy`) == FALSE) %>%
ggplot(aes(x = `Total Life Expectancy`)) + 
  geom_histogram(fill = "blue") + 
  labs(
    x = "Life Expectancy",
    y = "Frequency",
    title = "Distribution of Total Life Expectancy"
  ) 

#Summary stats for total life expectancy
full_data %>%
  select(`Total Life Expectancy`) %>%
   filter(is.na(`Total Life Expectancy`) == FALSE) %>%
summary(`Total Life Expectancy`)

#Distribution of fertility rates - not great, don't include - lots of missingness
full_data %>%
  filter(Year == 2018) %>%
  filter(is.na(`Fertility rate, total (births per woman)`) == FALSE) %>%
ggplot(aes(x = `Fertility rate, total (births per woman)`)) + 
  geom_histogram(fill = "blue") + 
  labs(
    x = "Fertility Rate",
    y = "Frequency",
    title = "Distribution of Fertility Rates"
  ) 

#Summary stats for fertility rates (with missingness)
full_data %>%
  select(`Fertility rate, total (births per woman)`) %>%
summary(`Fertility rate, total (births per woman)`)



#Distribution of mortality rates - not great, don't include - lots of missingness
full_data %>%
  filter(Year == 2018) %>%
  filter(is.na(`Mortality rate, under-5 (per 1,000 live births)`) == FALSE) %>%
ggplot(aes(x = `Mortality rate, under-5 (per 1,000 live births)`)) + 
  geom_histogram(fill = "blue") + 
  labs(
    x = "Mortality Rates Under 5",
    y = "Frequency",
    title = "Distribution of Mortality Rates"
  ) 

#Summary stats for mortality rates (with missingness)
full_data %>%
  select(`Mortality rate, under-5 (per 1,000 live births)`) %>%
summary(`Mortality rate, under-5 (per 1,000 live births)`)


#Maps for all three health outcomes - troubleshoot why colors not displayed
ggplot(data = healthspending.world) +
    geom_sf(aes(fill = `Mortality rate, under-5 (per 1,000 live births)`)) +
    scale_fill_viridis_c(option = "plasma") +
    labs(x = "Longitude",
       y = "Latitude",
       title = "Mortality Rates Around the World",
       fill = "Mortality Rates Under 5")

ggplot(data = healthspending.world) +
    geom_sf(aes(fill = `Fertility rate, total (births per woman)`)) +
    scale_fill_viridis_c(option = "plasma") +
    labs(x = "Longitude",
       y = "Latitude",
       title = "Fertility Rates Around the World",
       fill = "Fertility Rate")

ggplot(data = healthspending.world) +
    geom_sf(aes(fill = `Total Life Expectancy`)) +
    scale_fill_viridis_c(option = "plasma") +
    labs(x = "Longitude",
       y = "Latitude",
       title = "Total Life Expectancy Around the World",
       fill = "Total Life Expectancy")

#Plotting distributions of female vs male life expectancy - keep in mind that we can't facet them because separate variables so we'll just put next to each other on slide
full_data %>%
  filter(Year == 2018) %>%
  filter(is.na(`Female Life Expectancy`) == FALSE) %>%
ggplot(aes(x = `Female Life Expectancy`)) + 
  geom_histogram(fill = "blue") + 
  labs(
    x = "Female Life Expectancy",
    y = "Frequency",
    title = "Distribution of Female Life Expectancy"
  ) 

full_data %>%
  filter(Year == 2018) %>%
  filter(is.na(`Male Life Expectancy`) == FALSE) %>%
ggplot(aes(x = `Male Life Expectancy`)) + 
  geom_histogram(fill = "blue") + 
  labs(
    x = "Male Life Expectancy",
    y = "Frequency",
    title = "Distribution of Male Life Expectancy"
  ) 

#Now we're going to choose 5 countries and plot line graphs for trends in health outcomes over time
full_data %>%
  filter(`Country Name` == "Australia" | `Country Name` == "United States" |  `Country Name` == "Canada" |  `Country Name` == "China") %>%
ggplot(aes(x=Year, y=`Total Life Expectancy`, group = `Country Name`)) +
  geom_line(aes(linetype= `Country Name`))+
  geom_point(aes(shape=`Country Name`))

#Now we're going to choose 5 countries and plot line graphs for trends in health spending over time
full_data %>%
  filter(`Country Name` == "Australia" | `Country Name` == "United States"  |  `Country Name` == "China") %>%
ggplot(aes(x=Year, y=`Mortality rate, under-5 (per 1,000 live births)`, group = `Country Name`)) +
  geom_line(aes(linetype= `Country Name`))+
  geom_point(aes(shape=`Country Name`))

full_data %>%
  filter(`Country Name` == "Australia" | `Country Name` == "United States"  |  `Country Name` == "China") %>%
ggplot(aes(x=Year, y=`Fertility rate, total (births per woman)`, group = `Country Name`)) +
  geom_line(aes(linetype= `Country Name`))+
  geom_point(aes(shape=`Country Name`))
```
